#!/usr/bin/env bash
# Regenerate configmap.yaml from the page sources in this directory. The .html and
# .woff2 files are the source of truth; configmap.yaml is generated and must never be
# hand-edited. Run after every page change, then commit the sources and the ConfigMap
# together.
#
# The pages go in `data` as text. The fonts go in `binaryData`, base64 on ONE line
# each: Kubernetes decodes binaryData with StdEncoding, which rejects the newlines a
# wrapped block scalar would introduce. The lines are long on purpose.
set -euo pipefail
cd "$(dirname "$0")"

# The price table is filled from the live rate card at render time, so the page stays
# static and script-free. RATES_JSON overrides the fetch (tests, offline renders).
RATES_JSON="${RATES_JSON:-$(curl -fsS --max-time 20 https://api.nuved.io/v1/rates)}"
fill_rates() { # stdin: a page; stdout: the page with every <!--rate:X-->…<!--/rate--> filled
  RATES_JSON="$RATES_JSON" python3 -c '
import json, os, re, sys, datetime
c = json.loads(os.environ["RATES_JSON"])
def eur(x):
    s = f"{x:.4f}".rstrip("0").rstrip(".")
    return "€" + (s if "." in s else s + ".00")
since = datetime.datetime.fromisoformat(c["since"].replace("Z", "+00:00"))
vals = {
    "cpu": eur(c["cpu_micro_per_milli_hour"] * 1000 / 1e6),
    "mem": eur(c["mem_micro_per_gib_hour"] / 1e6),
    "disk": eur(c["disk_micro_per_gb_month"] / 1e6),
    "since": f"{since.day} {since:%B %Y}",
}
page = sys.stdin.read()
sys.stdout.write(re.sub(r"<!--rate:(\w+)-->.*?<!--/rate-->",
    lambda m: f"<!--rate:{m.group(1)}-->{vals[m.group(1)]}<!--/rate-->", page))'
}

PAGES=(index.html how-it-works.html)
FONTS=(schibsted-grotesk.woff2 ibm-plex-mono-400.woff2 ibm-plex-mono-500.woff2)
# Brand assets, served at /brand/ from their own ConfigMap so Authentik and mail
# clients have a stable address for the wordmark. Text and binary are split
# because a ConfigMap keeps them in different fields.
BRAND_TEXT=(nuved-wordmark.svg nuved-wordmark-dark.svg favicon.svg)
BRAND_BIN=(nuved-wordmark.png favicon.png)

{
  cat <<'HEAD'
# GENERATED by ./render.sh from the .html and .woff2 files in this directory — do not
# edit by hand.
# Every key here becomes a file in /usr/share/nginx/html, because the Deployment mounts
# the whole ConfigMap as that directory. So index.html is served at / and
# how-it-works.html at /how-it-works.html with no nginx configuration of our own, and
# the pages reach the fonts by their bare filenames.
# nginx reads the file per request, so a ConfigMap change reaches visitors without a
# restart (the kubelet refreshes a mounted ConfigMap within about a minute).
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-html
  labels:
    app: www
data:
HEAD
  for page in "${PAGES[@]}"; do
    printf '  %s: |\n' "$page"
    fill_rates < "$page" | sed 's/^/    /'
  done
  printf 'binaryData:\n'
  for font in "${FONTS[@]}"; do
    printf '  %s: ' "$font"
    base64 < "$font" | tr -d '\n'
    printf '\n'
  done
} > configmap.yaml

{
  cat <<'HEAD'
# GENERATED by ./render.sh from the files in brand/ — do not edit by hand.
# Mounted at /usr/share/nginx/brand and served at /brand/ by nginx.conf.yaml,
# which is where the day-long cache and the wide-open CORS header come from.
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-brand
  labels:
    app: www
data:
HEAD
  for a in "${BRAND_TEXT[@]}"; do
    printf '  %s: |\n' "$a"
    sed 's/^/    /' "brand/$a"
  done
  printf 'binaryData:\n'
  for a in "${BRAND_BIN[@]}"; do
    printf '  %s: ' "$a"
    base64 < "brand/$a" | tr -d '\n'
    printf '\n'
  done
} > brand.yaml

total=$(wc -c < configmap.yaml | tr -d ' ')
for f in "${PAGES[@]}" "${FONTS[@]}"; do
  printf '%-28s %7s bytes\n' "$f" "$(wc -c < "$f" | tr -d ' ')"
done
for a in "${BRAND_TEXT[@]}" "${BRAND_BIN[@]}"; do
  printf 'brand/%-22s %7s bytes\n' "$a" "$(wc -c < "brand/$a" | tr -d ' ')"
done
printf '%-28s %7s bytes\n' "brand.yaml" "$(wc -c < brand.yaml | tr -d ' ')"
printf '%-28s %7s bytes (ConfigMap objects are capped at 1 MiB = 1048576)\n' "configmap.yaml" "$total"
[ "$total" -lt 1048576 ] || { echo "configmap.yaml is over the 1 MiB ConfigMap limit" >&2; exit 1; }

# nginx reads its config once, at start; a changed checksum on the pod template makes
# Argo roll the pods when nginx.conf.yaml changes.
sum=$(shasum -a 256 nginx.conf.yaml | cut -c1-64)
python3 - "$sum" <<'PY'
import re, sys
p = "www.yaml"; s = open(p).read()
s2 = re.sub(r'(nuved\.io/nginx-conf-sha256: )"[0-9a-f]*"', r'\g<1>"%s"' % sys.argv[1], s)
assert s2 != s or sys.argv[1] in s, "annotation missing from www.yaml"
open(p, "w").write(s2)
PY
