#!/usr/bin/env bash
# Regenerate configmap.yaml from the HTML pages. The .html files are the source of
# truth; configmap.yaml is generated and must never be hand-edited.
# Run after every page change, then commit the pages and the ConfigMap together.
set -euo pipefail
cd "$(dirname "$0")"

PAGES=(index.html how-it-works.html)

{
  cat <<'HEAD'
# GENERATED by ./render.sh from the .html files in this directory — do not edit by hand.
# Every key here becomes a file in /usr/share/nginx/html, because the Deployment mounts
# the whole ConfigMap as that directory. So index.html is served at / and
# how-it-works.html at /how-it-works.html with no nginx configuration of our own.
# nginx reads the file per request, so a ConfigMap change reaches visitors without a
# restart (the kubelet refreshes a mounted ConfigMap within about a minute).
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-html
  labels:
    app: www
data:
HEAD
  for page in "${PAGES[@]}"; do
    printf '  %s: |\n' "$page"
    sed 's/^/    /' "$page"
  done
} > configmap.yaml

total=$(wc -c < configmap.yaml | tr -d ' ')
for page in "${PAGES[@]}"; do
  printf '%-20s %7s bytes\n' "$page" "$(wc -c < "$page" | tr -d ' ')"
done
printf '%-20s %7s bytes (ConfigMap objects are capped at 1 MiB = 1048576)\n' "configmap.yaml" "$total"
