#!/usr/bin/env bash
# Regenerate configmap.yaml from the page sources in this directory. The .html and
# .woff2 files are the source of truth; configmap.yaml is generated and must never be
# hand-edited. Run after every page change, then commit the sources and the ConfigMap
# together.
#
# The pages go in `data` as text. The fonts go in `binaryData`, base64 on ONE line
# each: Kubernetes decodes binaryData with StdEncoding, which rejects the newlines a
# wrapped block scalar would introduce. The lines are long on purpose.
set -euo pipefail
cd "$(dirname "$0")"

PAGES=(index.html how-it-works.html)
FONTS=(schibsted-grotesk.woff2 ibm-plex-mono-400.woff2 ibm-plex-mono-500.woff2)

{
  cat <<'HEAD'
# GENERATED by ./render.sh from the .html and .woff2 files in this directory — do not
# edit by hand.
# Every key here becomes a file in /usr/share/nginx/html, because the Deployment mounts
# the whole ConfigMap as that directory. So index.html is served at / and
# how-it-works.html at /how-it-works.html with no nginx configuration of our own, and
# the pages reach the fonts by their bare filenames.
# nginx reads the file per request, so a ConfigMap change reaches visitors without a
# restart (the kubelet refreshes a mounted ConfigMap within about a minute).
apiVersion: v1
kind: ConfigMap
metadata:
  name: www-html
  labels:
    app: www
data:
HEAD
  for page in "${PAGES[@]}"; do
    printf '  %s: |\n' "$page"
    sed 's/^/    /' "$page"
  done
  printf 'binaryData:\n'
  for font in "${FONTS[@]}"; do
    printf '  %s: ' "$font"
    base64 < "$font" | tr -d '\n'
    printf '\n'
  done
} > configmap.yaml

total=$(wc -c < configmap.yaml | tr -d ' ')
for f in "${PAGES[@]}" "${FONTS[@]}"; do
  printf '%-28s %7s bytes\n' "$f" "$(wc -c < "$f" | tr -d ' ')"
done
printf '%-28s %7s bytes (ConfigMap objects are capped at 1 MiB = 1048576)\n' "configmap.yaml" "$total"
[ "$total" -lt 1048576 ] || { echo "configmap.yaml is over the 1 MiB ConfigMap limit" >&2; exit 1; }
